{% set version = "2.3.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dbplyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dbplyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dbplyr/dbplyr_{{ version }}.tar.gz
  sha256: 7ce48918aaa6f96cd95ac1349f1654def129787e9f3b784307b458d4e03a75b4

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-blob >=1.2.0
    - r-cli >=3.4.1
    - r-dbi >=1.0.0
    - r-dplyr >=1.1.0
    - r-glue >=1.2.0
    - r-lifecycle >=1.0.3
    - r-magrittr
    - r-pillar >=1.5.0
    - r-purrr >=1.0.1
    - r-r6 >=2.2.2
    - r-rlang >=1.0.6
    - r-tibble >=1.4.2
    - r-tidyr >=1.3.0
    - r-tidyselect >=1.2.0
    - r-vctrs >=0.5.0
    - r-withr
  run:
    - r-base
    - r-blob >=1.2.0
    - r-cli >=3.4.1
    - r-dbi >=1.0.0
    - r-dplyr >=1.1.0
    - r-glue >=1.2.0
    - r-lifecycle >=1.0.3
    - r-magrittr
    - r-pillar >=1.5.0
    - r-purrr >=1.0.1
    - r-r6 >=2.2.2
    - r-rlang >=1.0.6
    - r-tibble >=1.4.2
    - r-tidyr >=1.3.0
    - r-tidyselect >=1.2.0
    - r-vctrs >=0.5.0
    - r-withr

test:
  commands:
    - $R -e "library('dbplyr')"           # [not win]
    - "\"%R%\" -e \"library('dbplyr')\""  # [win]

about:
  home: https://dbplyr.tidyverse.org/
  dev_url: https://github.com/tidyverse/dbplyr
  doc_url: https://dbplyr.tidyverse.org/reference/
  license: MIT
  summary: A 'dplyr' back end for databases that allows you to work with remote database tables as if they are in-memory data frames. Basic features works with any database that has a 'DBI' back end; more advanced features require 'SQL' translation to be provided by the package author.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
