{% set version = "1.2.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dbplyr
  version: {{ version|replace("-", "_") }}

source:
  fn: dbplyr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/dbplyr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/dbplyr/dbplyr_{{ version }}.tar.gz
  sha256: 9d410bb0055fffe10f1f8da55a5b24d98322c7b571d74df61427d5888332bc48

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-dbi >=0.5
    - r-r6
    - r-assertthat >=0.2.0
    - r-dplyr >=0.5.0.9004
    - r-glue
    - r-purrr
    - r-rlang >=0.1.0
    - r-tibble >=1.3.0.9007
    - r-tidyselect

  run:
    - r-base
    - r-dbi >=0.5
    - r-r6
    - r-assertthat >=0.2.0
    - r-dplyr >=0.5.0.9004
    - r-glue
    - r-purrr
    - r-rlang >=0.1.0
    - r-tibble >=1.3.0.9007
    - r-tidyselect

test:
  commands:
    - $R -e "library('dbplyr')"  # [not win]
    - "\"%R%\" -e \"library('dbplyr')\""  # [win]

about:
  home: https://github.com/tidyverse/dbplyr
  license: MIT
  summary: A 'dplyr' back end for databases that allows you to work with  remote database tables
    as if they are in-memory data frames. Basic features works with any database that
    has a 'DBI' back end; more advanced features  require 'SQL' translation to be provided
    by the package author.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
