appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: A0LUNopQvkKv7Zqy66VZuu6FswnCltehlTHxNMlUq2L+JE0ndK92O69aJ7YBUODLFyjHtcPRgcZ4sLog4j1JVzB6ai6iSA8/Qw7MEObSNByYsqrJcxySgOUx4/SFKCsweccSxjhTaixAFBpGU63+9T60aft9WjZ3RSr42+bXG8SUFgyFf9rYA3IqTYsRS7gI5QGfBX2x46a+E0SdNvx4kd6g4o3x+sSpT8CryDG/v7oGxhsnoiK/CapqW9/tHlKZeyvoif/Xt3SnXJ8PR972yU2F/D0DuDTWIyOiv4MVnuAhUHZAqL70JP3x8JZgtxBIhtwE3bKV98OUesFLROasfa97KpJp9cKdAzpJ1ryaM+OCE1OeuDxTOe6Wy6RKOeMcGbGjFK9//xIp4wREFp5NnI1RGiux1ypsPqBV9dQF9HEeKqlqN6VUtd0rtjRYsA8hH2rDIS1cResLJoY3mSUEwdwMWHsXfqoMjWUVI3d8rokWmzcP+Fu5QO7B9kIL+a968GZg7d5R8yIN546XWBHlhYPL2fZfTaRulzV11kjoGOpFVq4bw9IpFA2XlgRUoLDi8OdTkB2j0vQO3L+G066epYtj1XnvB2+Ts5egMo15S5ZwS5NM5LDOL/5yMp8pBIb+Vcgd8MaOfmfaZix70/o6GMJW4cVcF4Gpn3t0Yt4FR5c=}
bot:
  automerge: true
